### ISSUE TITLE
THANKS!

### ISSUE THREAD

**Issue by guyiac** [CiviCooP/org.civicoop.recurringcontributionsearch#1]
Not sure if there is a better way to give you feedback on this besides opening an issue (and if there is let me know), but I just wanted to thank you guys for this sweet little extension. I have a client where this functionality is SO HANDY - should really be part of core!  Really really nice, and well thought out, even the fields that you chose to display in the search results. Thank you!

**Comment by ErikHommel** [comment]
You make us blush @guyiac :-), thanks for the feedback!
